import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",  // Esse valor já está definido
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",  // Adiciona o favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title || 'Default Title'}</title>  {/* Fallback para título */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: "url('/window.svg')",  // Usando a imagem window.svg como fundo
          backgroundSize: "cover",  // Garante que a imagem cubra a tela inteira
          backgroundPosition: "center",  // Centraliza a imagem
          backgroundRepeat: "no-repeat",  // Evita que a imagem se repita
        }}
      >
        {/* Ícone ou elemento de imagem */}
        <img
          src="/window.svg"  // Imagem exibida diretamente
          alt="Window Icon"
          style={{
            position: "absolute",  // Ajusta a posição
            top: "20px",  // Exemplo de ajuste da posição
            left: "20px",  // Exemplo de ajuste da posição
            width: "100px",  // Tamanho ajustável
          }}
        />

        {/* Conteúdo da página */}
        {children}
      </body>
    </html>
  );
}